blank_issues_enabled: false
contact_links:
  - name: GitHub Security Bug Bounty
    url: https://github.com/Xia0xia0Xia0/Xia0xia0Xia0/issues/new/issue
    about: Please report security vulnerabilities here.
