name: Issue Report
description: Report a problem
body:
  - type: markdown
    attributes:
    value: test
- type: textarea
    id: descriptin
    attributes:
      label: Describe the issue
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser and platform
      description: If there is any chance at all that this is browser or platform related, please let us know which ones you tested. If IME or a virtual keyboard was involved, please mention which.
    validations:
      required: false
  - type: input
    id: try
    attributes:
      label: Reproduction link
      description: When practical, it helps a lot if you provide a script that reproduces the issue or another online code environment.
    validations:
      required: false
